### ISSUE TITLE
Doesn't fail on not found URL

### ISSUE THREAD

**Issue by dialex** [remarkjs/remark-validate-links#19]
Urls such as...

- https://www.npmjs.com/package/PageThatDoesNotExistAndReturns404
- https://gibberish
- http://somedummypage.com/

...do not return warnings or errors. I was not expecting this.

So this tool only validates links to internal pages? If that's so, it should be made explicit.

**Comment by wooorm** [comment]
@dialex Correct, that’s not supported, there are other tools that do that. Could you create a PR that makes the docs more clear?

**Comment by dialex** [comment]
Done @wooorm. Can you recommend me a tool to check for broken external links?

**Comment by wooorm** [comment]
Should be something here! https://github.com/remarkjs/remark-lint#list-of-external-rules

I’ll close this for now, we can discuss the PR on it’s own page (but I’ll do that later)
