### ISSUE TITLE
Request: Change warnings to errors

### ISSUE THREAD

**Issue by dialex** [remarkjs/remark-validate-links#21]
I want to run this tool as a step of our Continuous Integration in TravisCI. Since all issues are reported as "warnings" and the exit status of the tool is 0 (success), there's no way to automatically detect an error. 

I don't want to look at logs to find out there are issues. Is there any workaround?
As a quick fix you could return a non-zero exit status if there are warnings

**Comment by wooorm** [comment]
You can use `--quiet` on the remark cli to make warnings exit fatally!

**Comment by dialex** [comment]
That did not work. I forced a warning and the exit status was `0` (success). Any suggestions?
![screen shot 2018-02-16 at 09 27 03](https://user-images.githubusercontent.com/2140450/36301096-99b02f52-12fb-11e8-892b-e647659c3b48.png)

**Comment by wooorm** [comment]
Ah, sorry, it was late. I meant `--frail`. See the docs for more info: https://github.com/unifiedjs/unified-args

**Comment by dialex** [comment]
Thanks, works perfectly ;)
