### ISSUE TITLE
Option to ignore filename extensions

### ISSUE THREAD

**Issue by kruton** [remarkjs/remark-validate-links#22]
For Gatsby pages the `.md` is stripped off the file, so a link for a page named "src/pages/about-us.md" ends up being "/about-us/" (by default). It would be excellent to have the ability to ignore the filename extension to support link validation in Gatsby.

**Comment by wooorm** [comment]
Hmm, I feel that this is out of the scope of remark-validate-links. This project is very much about references between markdown files. I personally feel that gatsby should not just rewrite the files to different places, but also rewrite the links to markdown files to their new destinations.

If you’re looking for checking of whether URLs are live, maybe try [`remark-lint-no-dead-urls`](https://github.com/davidtheclark/remark-lint-no-dead-urls)?
