### ISSUE TITLE
Use native Object.assign instead of xtend

### ISSUE THREAD

**Issue by jimmywarting** [remarkjs/remark-validate-links#25]
[xtend](https://github.com/Raynos/xtend) can easily be replaced with [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

```js
Object.assign(a, b)
```

**Comment by wooorm** [comment]
Let’s discuss over on https://github.com/syntax-tree/hast-util-from-parse5/issues/8.
