### ISSUE TITLE
Disable lint

### ISSUE THREAD

**Issue by Scriptkiddi** [remarkjs/remark-validate-links#27]
Hey I'm currently trying to add ignore an url using https://github.com/remarkjs/remark-message-control. I can not seem to get it to work could it be because moduls.export is only passed a function thats never called

**Comment by wooorm** [comment]
Hey @Scriptkiddi! Thanks for raising this, but it’s very hard for us to help you like this. Please see [contributing.md](https://github.com/remarkjs/remark/blob/master/contributing.md#submitting-an-issue) for more info on how to create a better issue!

**Comment by Scriptkiddi** [comment]
Hey sorry I was in a rush, so what currently is not working for me, is the disable statement out of the remark-message-control plugin. As far as I have understood it I use the marker and together with the disable statement like this . I'm not completely sure what the marker is supposed to be for this plugin I would have guessed validate-link is that correct?

**Comment by wooorm** [comment]
@Scriptkiddi Still, no code, so it‘s really hard to help you out. This seems a question on how to use https://github.com/remarkjs/remark-message-control. Have you read those docs? Have you checked out an example of how it’s used (such as: https://github.com/remarkjs/remark-lint/blob/master/packages/remark-lint/index.js)

**Comment by Scriptkiddi** [comment]
I'm using the cli version of remark to check Markdown files for style consistency, so I really dont have code besides `remark -u validate-links .` and 
`

broken link

`
I'm trying to combine this package with the message control one I read both docs but I do not understand where the lint qualifier is coming from and if message control is a feature a plugin would have to support to work or can message control be used with the plugin knowing about it

**Comment by wooorm** [comment]
I investigated this, and unfortunately it won’t work. validate-links uses the file set to add more files when the CLI is running, and we check links (and create messages) when the file is completely processed already. When we’re checking the links, the syntax-tree is gone already, so we can’t inspect it to find these message control markers anymore.
Sorry, but this is not possible :'(

**Comment by Scriptkiddi** [comment]
Thanks for taking a look :D
