### ISSUE TITLE
There should be a way to ignore "repository" in package.json

### ISSUE THREAD

**Issue by NickHeiner** [remarkjs/remark-validate-links#28]
I have the following field in my `package.json`:

```json
  "repository": {
    "type": "git",
    "url": "ssh://git@stash.corp.netflix.com:7999/t2/tvui.git"
  },
```

When I run `remark`, I get the following error:

```
λ remark -u validate-links .

tools/tvui-tools-update-edge-scripts/README.md
  1:1  error  Error: remark-validate-links cannot parse `repository` (`ssh://git@stash.corp.netflix.com:7999/t2/tvui.git`)
```

That error is repeated at location `1:1` of every one of my 158 markdown files in this repo. It's a bit misleading to suggest that the error is with the markdown itself, and not with the config passed in. There should only be one error displayed to the user, before any files are checked.

But more pressingly, this issue blocks me from using this tool. I can't remove the `repository` field from `package.json`, because other tools rely on it. But if I pass a falsey value for `--use 'validate-links=repository:'`, the code reads from the `package.json` anyway.

I need a flag to say something like `--ignore-repository`. I'm happy to just forgo repository functionality and rely only on local checking.

Thanks!

**Comment by wooorm** [comment]
Hmm, this plugin strongly expects the files you’re processing to be part of a GitHub/Bitbucket/GitLab repository. Much of the file/path resolving is based on that.

Could you try passing in `repository: t2/tvui`, would something like that work?

**Comment by wooorm** [comment]
@NickHeiner Ping!

**Comment by NickHeiner** [comment]
Hi. Thanks for the follow-up. I was on vacation, so I didn't see this until now.

I'm a little surprised that passing a repository is necessary, because:

1. The [docs](https://github.com/remarkjs/remark-validate-links#configuration) make it sound optional:
    > When a repository is given or detected (supporting GitHub, GitLab, and Bitbucket), links to the files are normalized to the file-system.
1. Knowing the repository shouldn't be necessary to validate that local links (e.g. `[foo](./foo.md)`) are valid.

I suspect that passing `t2/tvui` would not work, because then the tool would assume that it's on GH.

Is there no mode that just ignores links to the files on the remote web host? (e.g. `https://github.com/org/repo/blob/file.md`)
