### ISSUE TITLE
Programmatic use: validate anchors in other files (like CLI)

### ISSUE THREAD

**Issue by DesignByOnyx** [remarkjs/remark-validate-links#38]
With the CLI it is possible to validate anchor references to other files: `[some link](another-file.md#some-anchor)`.

This is because the code path for the CLI accepts multiple files. However, the code path for programmatic use can only accept one file; as such it does not validate external anchors like the CLI.

It would be nice to be able to pass a set of files in for programmatic use. For example, my current situation looks like this:

```js
const processor = remark().use(validateLinks);

fastGlob('{,!(.git|node_modules)/}**/*.md')
  .then(paths => Promise.all(
    paths.map(p => vfile.read(p, 'utf8'))
  ))
  .then(vfiles => Promise.all(
    vfiles.map(file => processor.process(file))
  ));
```

As you can see, I already have a collection of files - and I would like to validate that cross references between files are valid. Is this possible today in a way that I'm not seeing?

**Comment by ChristianMurphy** [comment]
@DesignByOnyx I'd recommend using [unified engine](https://github.com/unifiedjs/unified-engine) for handling globs of files programmatically.
Using a combination of the [`processor`](https://github.com/unifiedjs/unified-engine/blob/master/doc/options.md#optionsprocessor), [`plugins`](https://github.com/unifiedjs/unified-engine/blob/master/doc/options.md#optionsplugins), and [`files`](https://github.com/unifiedjs/unified-engine/blob/master/doc/options.md#optionsfiles) can get the files processing through remark validate links the same way as the CLI would.

**Comment by DesignByOnyx** [comment]
Thank you! That ended up working perfectly. For anybody else who may come across this, I was able to change my existing code (above) to the following (with virtually no other changes to my code):

```js
    engine({
      processor: remark(),
      files: ['!(scripts|node_modules|.git)/**/*.md'],
      plugins: ['remark-validate-links'],
    }, (err, code, context) => {
      if(err) return reject(err);
      resolve(context.files);
    });
```
