### ISSUE TITLE
[feat] allow to setup `domain` for `repository`

### ISSUE THREAD

**Issue by evilebottnawi** [remarkjs/remark-validate-links#39]
Problem - we use self hosted `gitlab` and can't validate link like:
```md
[foo](https://gitlab.itgalaxy.company/itgalaxy/insteria/blob/master/foo);
```

Problem here https://github.com/remarkjs/remark-validate-links/blob/master/index.js#L73

Using
```
repository: "gitlab:itgalaxy/insteria"
```

Return
```
{ type: 'gitlab',
  protocols: [ 'git+ssh', 'git+https', 'ssh', 'https' ],
  domain: 'gitlab.com',
  treepath: 'tree',
  bugstemplate: 'https://{domain}/{user}/{project}/issues',
  tarballtemplate:
   'https://{domain}/{user}/{project}/repository/archive.tar.gz?ref={committish}',
  sshtemplate: 'git@{domain}:{user}/{project}.git{#committish}',
  sshurltemplate: 'git+ssh://git@{domain}/{user}/{project}.git{#committish}',
  browsetemplate: 'https://{domain}/{user}/{project}{/tree/committish}',
  browsefiletemplate:
   'https://{domain}/{user}/{project}/{treepath}/{committish}/{path}{#fragment}',
  docstemplate: 'https://{domain}/{user}/{project}{/tree/committish}#readme',
  httpstemplate:
   'git+https://{auth@}{domain}/{user}/{project}.git{#committish}',
  filetemplate: 'https://{domain}/{user}/{project}/raw/{committish}/{path}',
  shortcuttemplate: '{type}:{user}/{project}{#committish}',
  pathtemplate: '{user}/{project}{#committish}',
  pathmatch: /^[\/]([^\/]+)[\/]([^\/]+?)(?:[.]git|[\/])?$/,
  hashformat: [Function: formatHashFragment],
  protocols_re: /^(git\+ssh|git\+https|ssh|https):$/,
  user: 'itgalaxy',
  auth: null,
  project: 'insteria',
  committish: null,
  default: 'shortcut',
  opts: {} }
```

And all fine except `domain`, maybe we can add option to setup this? It is allow using this plugin with self hosted solution (for gitlab and github). Thanks

**Comment by wooorm** [comment]
Yeah I’m open to a PR for that. Would need solid test cases though, and I don’t have access to hosted GH so I can’t do that for GH, so I’d prefer to focus on GL now as you have access to that.

Also wondering if we could use https://github.com/npm/hosted-git-info better? It has some other functions that maybe the codebase here is duplicating?

**Comment by wooorm** [comment]
Wait, maybe, I think you passing `gitlab:itgalaxy/insteria` is actually invalid, as it points to the public hosted gitlab version? [More info](https://docs.npmjs.com/files/package.json#repository)

**Comment by evilebottnawi** [comment]
@wooorm yes, it is workaround for self hosted, but it is invalid so i open issue.
`hosted-git-info` is not support self hosted gitlab (and github).

I investigate code better, maybe we can implement `repositoryInfo` option as function/object what allow to defined any custom data. I give you feedback after investigate :+1:

**Comment by evilebottnawi** [comment]
@wooorm thanks for PR, can we do release?

**Comment by wooorm** [comment]
Soon, unified and remark both need majors, and a couple plugins and other projects in their ecosystems as well. So I’d like to coordinate all that together.

**Comment by evilebottnawi** [comment]
@wooorm thanks for feedback, not high priority, wait major new release, maybe we can solve some bugs in remark for prettier too :smile:
