### ISSUE TITLE
Custom slug generation

### ISSUE THREAD

**Issue by Livven** [remarkjs/remark-validate-links#40]
Could there be an option to override the slug generation algorithm by specifying a custom function? Or more specifically, the use case for me would be ignoring custom HTML/React/Vue components in headings, e.g. VuePress allows you to add [custom badges](https://vuepress.vuejs.org/guide/using-vue.html#badge) which are not used in the slug.

For example `### Heading <Badge text="1.0"/>` should generate a slug of `heading` rather than `heading-badge-text10-`.

**Comment by wooorm** [comment]
You can overwrite the slugs by setting a `data.id` property:

https://github.com/remarkjs/remark-validate-links/blob/caa1f9fa8ca09567951cf28f9252f642ab36ad9a/index.js#L188-L192

**Comment by Livven** [comment]
Seems like that would require creating the slug manually and putting it somewhere in the Markdown?

**Comment by wooorm** [comment]
Yes, you’ll have to create slugs yourself if you want custom slugs!
You can create a plugin, and use it before `remark-validate-links`. See [**Create a plugin**](https://unified.js.org/create-a-plugin.html). You probably need [`unist-util-visit`](https://github.com/syntax-tree/unist-util-visit).

For example, something along these pseudocode lines:

```js
var visit = require('unist-util-visit')

module.exports = customSlugs

function customSlugs() {
  return transformer
}

function transformer(tree) {
  visit(tree, 'heading', visitor)
}

function visitor(node) {
  var data = node.data || (node.data = {})
  data.id = someCustomSlugAlgorithm(node)
}
```
