### ISSUE TITLE
Allow mixed case for headings

### ISSUE THREAD

**Issue by pajachiet** [remarkjs/remark-validate-links#41]
### Subject of the issue

`remark-validate-links` should authorize uppercase headings.

Currently, it authorize uppercase or mixed case link to files, but breaks for headings.

URL should be generally treated as case insensitive (cf [comment](https://github.com/vuelidate/vuelidate/issues/220#issuecomment-346521520)). 

### Your environment

*   **OS**: MacOs
*   **Packages**: 
"dependencies": {
    "remark": "^10.0.1",
    "remark-cli": "^6.0.1",
    "remark-lint": "^6.0.4",
    "remark-lint-no-dead-urls": "^0.4.1",
    "remark-validate-links": "^8.0.0",
    "vuepress": ">= v1.0.0-alpha.47"
  },

**Comment by wooorm** [comment]
Could you provide an example of **actual** behaviour and **expected** behaviour? Such as, some Markdown?

**Comment by pajachiet** [comment]
Sorry for the absence of example. I can see you already fixed it. Thanks a lot ! 🙏
