### ISSUE TITLE
Escape local folders containing #

### ISSUE THREAD

**Issue by kellyselden** [remarkjs/remark-validate-links#42]
### Subject of the feature

I'd like to validate local paths that include a "#".

### Problem

An example is `[src/acceptance/#smoke/apps-test.js](../src/acceptance/#smoke/apps-test.js)`. This of course doesn't work because the "#" is treated as a fragment. I was wondering if we could add an escape character or similar to support this? Perhaps `\#smoke` or `%23smoke`?

### Alternatives

I could remove the "#" from the folder names, but they relate to an existing system that is not going to change.

**Comment by wooorm** [comment]
Interesting.
We could do something with files including a `#` number sign, to map them properly to URLs, with encoding.
But `../src/acceptance/#smoke/apps-test.js` is a number sign in a URL, and that shouldn’t work, because it’s not encoded.
How are you rendering the Markdown, and does the URL work?

**Comment by kellyselden** [comment]
Ah I see what you're saying. You are right. If it isn't rendering correctly in standard markdown, then there's not that much this plugin can build upon.

**Comment by wooorm** [comment]
Right, true... I’m not entirely sure how to handle this issue. I guess you can have hashes in file paths, but as it doesn’t work in URLs, there isn’t much we can do. Closing this.

**Comment by kellyselden** [comment]
Success. I was able to get it to render correctly in vscode, and clicking follows the link. I switched it to `[src/acceptance/#smoke/apps-test.js](../src/acceptance/%23smoke/apps-test.js)`. So I think it is solvable via this plugin. I don't even think we need an escape character, just a code tweak somewhere. Do you mind reopening?
