### ISSUE TITLE
Absolute link in self-hosted repo is not validate

### ISSUE THREAD

**Issue by evilebottnawi** [remarkjs/remark-validate-links#46]
### Subject of the issue

Absolute link not validate in self-hosted repo

This is *not* a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/unified/remark)

### Your environment

*   **OS**: ubuntu
*   **Packages**: remark-validate-links@7.0.0
*   **Env**: node v10.15.2

### Steps to reproduce

- Create `test.md` with content:
```md
[foo](https://gitlab.itgalaxy.company/itgalaxy/insteria/blob/master/.editorconfigs)
```

Note `.editorconfigs` doesn't exist in repo, I specifically made a mistake in the file name, added `s` at end.
- configuration:
```
"use strict";

module.exports = {
  plugins: [
    "remark-preset-lint-itgalaxy",
    [
      "remark-validate-links",
      {
        hostname: 'gitlab.itgalaxy.company',
        prefix: '/itgalaxy/insteria/blob/',
      }
    ]
  ]
};

```

- run remark: `remark . -f -q -i .gitignore`

It it self-hosted gitlab, i tried debug and find what `config` [here](https://github.com/remarkjs/remark-validate-links/blob/master/lib/find/find.js#L117) has 
```
{ prefix: '',
  headingPrefix: '#',
  lines: false,
  hostname: null,
  path:
   '/home/evilebottnawi/IdeaProjects/insteria/wp-content/themes/insteria/README.md',
  base:
   '/home/evilebottnawi/IdeaProjects/insteria/wp-content/themes/insteria',
  root:
   '/home/evilebottnawi/IdeaProjects/insteria/wp-content/themes/insteria' }
```
value, so absolute link is skipped.

Looks my configuration is not respected, maybe `remark-validate-links` get output from `git` command and doesn't respect my configuration.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

Expected error

### Actual behaviour

No error.

```
[foo](https://gitlab.itgalaxy.company/itgalaxy/insteria/blob/master/.editorconfigs)
README.md: no issues found
```

**Comment by wooorm** [comment]
I think the self hosted info isn't passed a long properly, as your debugging console.log found. That config should be under a urlConfig key, could you check if that works?

**Comment by evilebottnawi** [comment]
```js
console.log(urlConfig)
process.exit();
```

output:
```
{ prefix: '', headingPrefix: '#', lines: false, hostname: null }
```

Maybe helpful, from "package.json":
```
"repository": {
    "type": "git",
    "url": "https://gitlab.itgalaxy.company/itgalaxy/insteria.git"
  }
```

**Comment by wooorm** [comment]
Please read my comment and the readme again carefully, I explained the solution above!

**Comment by evilebottnawi** [comment]
@wooorm please clarify, i can't understand

**Comment by wooorm** [comment]
Prefix and hostname should be in an object, urlConfig.

**Comment by wooorm** [comment]
https://github.com/remarkjs/remark-validate-links/blob/13a54a538a86fcb894845933e90f0fc398c1d85a/test/index.js#L1020

**Comment by evilebottnawi** [comment]
hm, above i written my configuration, something wrong?
```js
"use strict";

module.exports = {
  plugins: [
    "remark-preset-lint-itgalaxy",
    [
      "remark-validate-links",
      {
        hostname: 'gitlab.itgalaxy.company',
        prefix: '/itgalaxy/insteria/blob/',
      }
    ]
  ]
};

```

**Comment by wooorm** [comment]
You're missing the extra needed object, I'm on my phone so it's hard to type, but:

'remark-validate-links', {urlConfig: {hostname:..., prefix:...}}

**Comment by evilebottnawi** [comment]
oh, i see, thanks, maybe we can improve docs with full example? Because it was misleading for me :smile:

**Comment by wooorm** [comment]
Ahh, okay, PR welcome!
