### ISSUE TITLE
Links are failing when the link is using any of the restricted names like "constructor"/"concat" etc.

### ISSUE THREAD

**Issue by KishoreNemalipuri** [remarkjs/remark-validate-links#61]
### Subject of the issue
Links with a restricted name like `#constructor` is failing to validate.

Describe your issue here.
If the example.md is as below:

```
# Test file
## Constructor
[constructor](example.md#constructor)

```
Validation of this fails with  the below  error:
```
(node:65188) UnhandledPromiseRejectionWarning: TypeError: hashes.push is not a function
    at addReference (...../node_modules/remark-validate-links/lib/find/find.js:121:12)
    at mark (..../node_modules/remark-validate-links/lib/find/find.js:83:11)
```

And the reason for it is:
in [find.js](https://github.com/remarkjs/remark-validate-links/blob/84959749ac9aa204888a8f748f3f6601fb8be544/lib/find/find.js#L116)

we are retrieving the hash value using 
```
var hashes = refs[hash] || (refs[hash] = [])
```
And this returns a function (when hash = "constructor") - so it will not allow the next line to be executed properly.

```
hashes.push(node)
```
This line throws the above error mentioned.

### Your environment

*   **OS**: mac
*   **Packages**: remark/micromark
*   **Env**: node > 14

### Steps to reproduce

Create a markdown named : example.md with the below content

```
# Test file
## Constructor
[constructor](example.md#constructor)

```
And run usual `remark -u validate-links .`

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?

### Actual behavior

What happens instead?

**Comment by wooorm** [comment]
Nice find, released!

**Comment by KishoreNemalipuri** [comment]
> Nice find, released!

Thanks for the quick fix. Really appreciate it.
