### ISSUE TITLE
Support [[wikilinks]]

### ISSUE THREAD

**Issue by UlisseMini** [remarkjs/remark-validate-links#66]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Trying to validate local [[wikilinks]] using [remark-wiki-link](https://github.com/landakram/remark-wiki-link) and give warnings when they don't exist

### Solution

It should use the link in `wikilink.data.hProperties.href` to check local files

### Alternatives

Perhaps there's a way to transform wikilinks -> normal markdown links before using remark-validate-links. I could not find a way to do so in the wikilinks docs, and I feel this should "just work"

Or perhaps this should be done on the rehype level? I found [rehype-url-inspector](https://github.com/JS-DevTools/rehype-url-inspector) but it appears to be abandoned. I might make my own clone of remark-validate-links for rehype

**Comment by wooorm** [comment]
We can add hast support, which will solve this: a `hName: 'a'`, then look for the `hProperties.href`. Something like it is already done for `id`s: https://github.com/remarkjs/remark-validate-links#integration.

Want to work on a PR?

**Comment by UlisseMini** [comment]
> We can add hast support, which will solve this: a `hName: 'a'`, then look for the `hProperties.href`. Something like it is already done for `id`s: https://github.com/remarkjs/remark-validate-links#integration.
> 
> Want to work on a PR?

Sure! I'll work on a PR

**Comment by UlisseMini** [comment]
I've been busy and I haven't gotten to this, but I will eventually (just letting people know the issue isn't dead)
