### ISSUE TITLE
Headings with inline comments are slugged incorrectly

### ISSUE THREAD

**Issue by djmcgreal-cc** [remarkjs/remark-validate-links#73]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

12.1.0

### Steps to reproduce

Run this markdown:
```markdown
# Run a container whose image is pulled from internal GitLab <!-- comment -->

[Link](#run-a-container-whose-image-is-pulled-from-internal-gitlab)
```

Through remark-validate-links:
`remark --use remark-validate-links`

Here's the same markdown to show the GitHub heading link doesn't include _----comment----_ at the end:

# Run a container whose image is pulled from internal GitLab 

[Link](#run-a-container-whose-image-is-pulled-from-internal-gitlab)

### Expected behavior

Shouldn't include inline comments as heading identifier. I looked at the code and it's the node toString that gets passed to the slugger, so it should probably be removed beforehand, as it's not printable, which is what the slugger docs ask to be passed.

### Actual behavior

```
## Run a container whose image is pulled from internal GitLab <!-- comment -->

[Link](#run-a-container-whose-image-is-pulled-from-internal-gitlab)
validate-links-bug.md
  3:1-3:68  warning  Link to unknown heading: `run-a-container-whose-image-is-pulled-from-internal-gitlab`. Did you mean `run-a-container-whose-image-is-pulled-from-internal-gitlab----comment---`  missing-heading  remark-validate-links

⚠ 1 warning
```

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Thanks for your report.
I’ve fixed handling of HTML in headings to match GitHub.

Please note that the href you use in the link as your desired output, does not match how GitHub works. `## a <!-- b -->` turns into `a-`, not `a`.

As the text you use includes the word Gitlab, you might be using Gitlab. Perhaps the link you use is specific to Gitlab. We match GitHub. If you use Gitlab, please remove the comment from your heading.

**Comment by djmcgreal-cc** [comment]
Thanks a lot! And indeed, I'd spotted that too :)

**Comment by djmcgreal-cc** [comment]
Ay chance of a new release, @wooorm ? I tried to install with `npm install https://github.com/remarkjs/remark-validate-links` but somehow that method won't let me use it, whereas from the npm package release, it does.

**Comment by wooorm** [comment]
Done in [12.1.1](https://github.com/remarkjs/remark-validate-links/releases/tag/12.1.1)!

**Comment by djmcgreal-cc** [comment]
Thank you!
