### ISSUE TITLE
v13.0.2 introduced bug in detecting static assets 

### ISSUE THREAD

**Issue by dereknola** [remarkjs/remark-validate-links#78]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

13.0.2

### Link to runnable example

https://github.com/rancher/rke2-docs/actions/runs/11658790536/job/32458348363?pr=277

### Steps to reproduce

Prior to 13.02, usage of assets under the `root/static/` folder via Docusarous Static Assests support https://docusaurus.io/docs/static-assets did not trigger broken links.

### Expected behavior

For example, https://github.com/rancher/rke2-docs/blob/main/docs/security/fips_support.md?plain=1#L7, which points to a PDF, works correctly on the actual website, https://docs.rke2.io/security/fips_support. This is because Docusarous will 
> Docusaurus will try to look for it in both static/img/docusaurus.png and public/img/docusaurus.png. The link will then be converted to a require() call instead of staying as a URL.

The remarks-validate-links should not identify this link as broken.

### Actual behavior

The remarks-validate-links identify this link as broken.

### Affected runtime and version

node@18.19.1

### Affected package manager and version

yarn version v1.22.22

### Build and bundle tools

Docusaurus

**Comment by wooorm** [comment]
Hi!

If I go to https://github.com/rancher/rke2-docs/blob/main/docs/security/fips_support.md, and click that link, it 404s.

Same for the other things, if I go to https://github.com/rancher/rke2-docs/blob/main/docs/architecture.md, that image does not show.

This is covered by the paragraph “This is specifically for Git repos. Like this one. Not for say a website” in the intro and the “When should I use this?” section in the readme.

For a website, which uses more complex algorithms to look up things, as you describe for docusaurus with both `static` and `public`, that’s something dependent on particular tools, not something this tool does.

Perhaps https://github.com/remarkjs/remark-lint-no-dead-urls is what you are looking for?

**Comment by dereknola** [comment]
Unfortunately, https://github.com/remarkjs/remark-lint-no-dead-urls  only covers "external" link, while your plugin which checks "internal" links. 

I take your point that this is only intended for git repos and not websites. Worst case I can pin the dependency and tell dependabot to ignore it. 

I bring this issue up only because previous versions did not have this issue and thus this is an unexpected change in functionality. 

https://xkcd.com/1172/

**Comment by wooorm** [comment]
`remark-lint-no-dead-urls` is not limited to external links: when it is known what the `href` of a page is, it can resolve things relative to it (this is the internal you mean I think?)

Now, plugins are configured “in total”, not per file. So while there is one `from` option, you probably need to set an `origin` and `pathname` in `file.data.meta`: https://github.com/remarkjs/remark-lint-no-dead-urls#options

Right, xkcd.com/1172](https://xkcd.com/1172/ indeed 😅

**Comment by dereknola** [comment]
Thanks I will try that approach.
